# Generated by Django 5.2.6 on 2025-09-18 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corredor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idade', models.IntegerField()),
                ('genero', models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Outro', 'Outro')], max_length=20)),
                ('estado_civil', models.CharField(choices=[('Solteiro(a)', 'Solteiro(a)'), ('Casado(a)', 'Casado(a)'), ('Divorciado(a)', 'Divorciado(a)'), ('Viúvo(a)', 'Viúvo(a)')], max_length=20)),
                ('escolaridade', models.CharField(max_length=50)),
                ('profissao', models.CharField(max_length=100)),
                ('renda_familiar_mensal', models.CharField()),
                ('tempo_pratica_corrida', models.CharField(max_length=50)),
                ('frequencia_corrida', models.CharField(max_length=50)),
                ('participacao_corridas', models.BooleanField(default=False)),
                ('motivacao_principal', models.CharField(max_length=200)),
                ('faz_parte_grupo_corrida', models.BooleanField(default=False)),
                ('onde_costuma_correr', models.CharField(max_length=200)),
            ],
        ),
    ]
