# Generated by Django 5.2.6 on 2025-09-19 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corredor',
            name='idade',
            field=models.CharField(choices=[('18-24', '18 a 24'), ('25-34', '25 a 34'), ('35-44', '35 a 44'), ('45-54', '45 a 54'), ('55-64', '55 a 64'), ('65+', '65 ou mais')], max_length=5),
        ),
    ]
