# Generated by Django 5.2.6 on 2025-09-19 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_corredor_idade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corredor',
            name='faz_parte_grupo_corrida',
        ),
        migrations.RemoveField(
            model_name='corredor',
            name='frequencia_corrida',
        ),
        migrations.RemoveField(
            model_name='corredor',
            name='motivacao_principal',
        ),
        migrations.RemoveField(
            model_name='corredor',
            name='onde_costuma_correr',
        ),
        migrations.RemoveField(
            model_name='corredor',
            name='participacao_corridas',
        ),
        migrations.RemoveField(
            model_name='corredor',
            name='tempo_pratica_corrida',
        ),
        migrations.AddField(
            model_name='corredor',
            name='frequencia',
            field=models.CharField(blank=True, choices=[('1 vez por semana', '1 vez por semana'), ('2 a 3 vezes por semana', '2 a 3 vezes por semana'), ('4 a 5 vezes por semana', '4 a 5 vezes por semana'), ('Todos os dias', 'Todos os dias')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='corredor',
            name='grupo_corrida',
            field=models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], default='', max_length=5),
        ),
        migrations.AddField(
            model_name='corredor',
            name='local_corrida',
            field=models.CharField(blank=True, choices=[('Parque Municipal', 'Parque Municipal'), ('Rua', 'Rua'), ('Academia (esteira)', 'Academia (esteira)'), ('Outro', 'Outro')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='corredor',
            name='local_corrida_outro',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='corredor',
            name='motivacao',
            field=models.CharField(blank=True, choices=[('Saúde / Bem-estar', 'Saúde / Bem-estar'), ('Estética / Emagrecimento', 'Estética / Emagrecimento'), ('Desempenho / Superação pessoal', 'Desempenho / Superação pessoal'), ('Socialização', 'Socialização'), ('Redução do estresse', 'Redução do estresse')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='corredor',
            name='participacao',
            field=models.CharField(blank=True, choices=[('Sim, regularmente', 'Sim, regularmente'), ('Sim, ocasionalmente', 'Sim, ocasionalmente'), ('Não', 'Não')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='corredor',
            name='tempo_pratica',
            field=models.CharField(blank=True, choices=[('Menos de 6 meses', 'Menos de 6 meses'), ('De 6 meses a 1 ano', 'De 6 meses a 1 ano'), ('De 1 a 2 anos', 'De 1 a 2 anos'), ('Mais de 2 anos', 'Mais de 2 anos')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='corredor',
            name='escolaridade',
            field=models.CharField(blank=True, choices=[('Ensino fundamental incompleto', 'Ensino fundamental incompleto'), ('Ensino fundamental completo', 'Ensino fundamental completo'), ('Ensino médio incompleto', 'Ensino médio incompleto'), ('Ensino médio completo', 'Ensino médio completo'), ('Ensino superior incompleto', 'Ensino superior incompleto'), ('Ensino superior completo', 'Ensino superior completo'), ('Pós-graduação(especialização, mestrado, doutorado)', 'Pós-graduação(especialização, mestrado, doutorado)')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='corredor',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('Solteiro(a)', 'Solteiro(a)'), ('Casado(a) / União Estável', 'Casado(a) / União Estável'), ('Divorciado(a)', 'Divorciado(a)'), ('Viúvo(a)', 'Viúvo(a)')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='corredor',
            name='genero',
            field=models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Outro', 'Outro')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='corredor',
            name='idade',
            field=models.CharField(blank=True, choices=[('18 a 24', '18 a 24'), ('25 a 34', '25 a 34'), ('35 a 44', '35 a 44'), ('45 a 54', '45 a 54'), ('55 a 64', '55 a 64'), ('65+', '65 ou mais')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='corredor',
            name='renda_familiar_mensal',
            field=models.CharField(blank=True, choices=[('Até 1 salário mínimo', 'Até 1 salário mínimo'), ('De 1 a 2 salários mínimos', 'De 1 a 2 salários mínimos'), ('De 2 a 3 salários mínimos', 'De 2 a 3 salários mínimos'), ('De 3 a 5 salários mínimos', 'De 3 a 5 salários mínimos'), ('De 5 a 100 salários mínimos', 'De 5 a 100 salários mínimos'), ('Acima de 100 salários mínimos', 'Acima de 100 salários mínimos'), ('Prefiro não informar', 'Prefiro não informar')], default='', max_length=100),
        ),
    ]
