# Generated by Django 5.2.6 on 2025-09-19 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_corredor_faz_parte_grupo_corrida_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corredor',
            name='local_corrida_outro',
        ),
        migrations.AlterField(
            model_name='corredor',
            name='local_corrida',
            field=models.CharField(blank=True, choices=[('Parque Municipal', 'Parque Municipal'), ('Rua', 'Rua'), ('Academia (esteira)', 'Academia (esteira)')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='corredor',
            name='renda_familiar_mensal',
            field=models.CharField(blank=True, choices=[('Até 1 salário mínimo', 'Até 1 salário mínimo'), ('De 1 a 2 salários mínimos', 'De 1 a 2 salários mínimos'), ('De 2 a 3 salários mínimos', 'De 2 a 3 salários mínimos'), ('De 3 a 5 salários mínimos', 'De 3 a 5 salários mínimos'), ('De 5 a 10 salários mínimos', 'De 5 a 10 salários mínimos'), ('Acima de 10 salários mínimos', 'Acima de 10 salários mínimos'), ('Prefiro não informar', 'Prefiro não informar')], default='', max_length=100),
        ),
    ]
